"""The two schema constants must declare the same shape.

save_plan inserts into a2a_messages positionally with 11 unnamed values, so
column ORDER is load-bearing, not just column names.
"""

import re

from flaskapp.database import _NOW, SCHEMA_POSTGRES, SCHEMA_SQLITE

TABLE = re.compile(
    r"CREATE TABLE IF NOT EXISTS (\w+) \((.*?)\n\);", re.DOTALL
)


def columns(schema: str) -> dict[str, list[str]]:
    tables = {}
    for name, body in TABLE.findall(schema):
        names = []
        for line in body.splitlines():
            line = line.strip()
            if not line or line.startswith("--") or line.upper().startswith(
                ("PRIMARY KEY", "UNIQUE", "CHECK", "FOREIGN KEY")
            ):
                continue
            names.append(line.split()[0])
        tables[name] = names
    return tables


def test_both_schemas_declare_the_same_tables():
    assert set(columns(SCHEMA_SQLITE)) == set(columns(SCHEMA_POSTGRES))


def test_both_schemas_declare_the_same_columns_in_the_same_order():
    sqlite_tables, postgres_tables = columns(SCHEMA_SQLITE), columns(SCHEMA_POSTGRES)
    for table, names in sqlite_tables.items():
        assert names == postgres_tables[table], f"{table} column order differs"


# The complete list of differences the design permits between the two schema
# texts. Anything else that differs is a defect in one of them, and the
# line-for-line test below is what says so. Name-and-order comparison alone
# could not see a dropped CHECK, a NOT NULL turned nullable, or an
# ON DELETE CASCADE quietly demoted to SET NULL.
TRANSLATIONS = (
    ("INTEGER PRIMARY KEY AUTOINCREMENT",
     "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    ("TEXT NOT NULL COLLATE NOCASE UNIQUE", "CITEXT NOT NULL UNIQUE"),
    ("DEFAULT CURRENT_TIMESTAMP", f"DEFAULT {_NOW}"),
    (" REAL", " DOUBLE PRECISION"),
)

INDEX = re.compile(r"(CREATE INDEX IF NOT EXISTS .*?;)", re.DOTALL)


def translated(line: str) -> str:
    for sqlite_text, postgres_text in TRANSLATIONS:
        line = line.replace(sqlite_text, postgres_text)
    return line


def definitions(schema: str) -> dict[str, list[str]]:
    """Whole declaration lines, not just the column name at the front."""
    tables = {}
    for name, body in TABLE.findall(schema):
        lines = [
            line.strip() for line in body.splitlines()
            if line.strip() and not line.strip().startswith("--")
        ]
        tables[name] = lines
    return tables


def test_types_defaults_and_constraints_match_line_for_line():
    sqlite_tables = definitions(SCHEMA_SQLITE)
    postgres_tables = definitions(SCHEMA_POSTGRES)
    for table, lines in sqlite_tables.items():
        assert [translated(line) for line in lines] == postgres_tables[table], (
            f"{table} differs beyond the permitted dialect translations"
        )


def test_no_sqlite_type_or_default_survives_untranslated_into_postgres():
    """Belt and braces: the SQLite-only spellings must be absent from Postgres."""
    for sqlite_text, _ in TRANSLATIONS:
        assert sqlite_text not in SCHEMA_POSTGRES, f"{sqlite_text!r} leaked"
    assert "PRAGMA" not in SCHEMA_POSTGRES
    assert "CITEXT" in SCHEMA_POSTGRES


def test_both_schemas_declare_the_same_indexes():
    def normalize(schema: str) -> list[str]:
        return [" ".join(match.split()) for match in INDEX.findall(schema)]

    assert normalize(SCHEMA_SQLITE) == normalize(SCHEMA_POSTGRES)


def test_the_specialist_roster_matches_the_graph():
    """`safeguards.SPECIALIST_NAMES` must list exactly the graph's specialists.

    safeguards declares its own copy so the deterministic layer does not depend
    on how the workflow is composed. That independence is only safe while the
    two agree: a specialist added to the graph but missing here would never be
    reported as unconsulted, and the traveller would not be told it was skipped.
    """
    from flaskapp.travel_ai.graph import SPECIALISTS
    from flaskapp.travel_ai.safeguards import SPECIALIST_NAMES

    assert set(SPECIALIST_NAMES) == set(SPECIALISTS)
