"""Seed rows for Flight Agent: the golden-scenario flights plus a broader,
generated inventory across 5 routes for realistic-sized testing.

`GOLDEN_SCENARIO_FLIGHTS` mirrors localfolder/db_schema.md section 7 ("the
hardest scenario"): wheelchair user, budget SGD 4,000, SIN -> Tokyo (NRT),
depart 2026-09-01. SQ636 is the cheap red-eye arriving 23:40 that Hotel/
Transport later finds infeasible; SQ632 is the mid-priced option arriving
15:10 that the flow renegotiates to once budget is exceeded. Kept as
literal, unchanging Python objects — golden JSON scenarios (tests/golden/
flight_scenarios.json) and several unit tests hard-code their exact prices/
times, so nothing here should ever edit these 4 rows; add new flights
instead.

The other 100 rows come from `seed_data_extended.csv`, generated by
scripts/generate_flight_seed_csv.py (SIN <-> NRT/LHR/SYD/BKK/HKG, mixed
full-service/budget carriers, cabins, prices, and seat inventory) — a handful
of hand-picked flights isn't enough to exercise ranking/filtering meaningfully
or look like a real dataset; see that script's docstring for how it was
derived and why it's deterministic (same output every regeneration). The
extended rows carry `seat_inventory`; the 4 golden rows deliberately leave it
None (their scenarios predate seat modelling and don't need it, and their
2026-09-01/05 dates don't collide with any extended-row date, so seat rows
never interfere with the golden scenarios).

Plain Python data, not tied to any database — see flight/__init__.py.
Prices are illustrative SGD figures, not real fares (db_schema.md rule 3).
"""

from __future__ import annotations

import csv
from pathlib import Path

from flaskapp.travel_ai.agents.flight_agent.schemas import FlightInventoryItem, SeatInventory

_TRUE_STRINGS = {"true", "1", "yes"}


def _seat_inventory_from_row(row: dict) -> SeatInventory:
    return SeatInventory(
        window_available=int(row["seat_window_available"]),
        aisle_available=int(row["seat_aisle_available"]),
        max_adjacent_block=int(row["seat_max_adjacent_block"]),
        accessible_available=int(row["seat_accessible_available"]),
        standard_fee=float(row["seat_standard_fee"]),
        extra_legroom_available=int(row["seat_extra_legroom_available"]),
        extra_legroom_fee=float(row["seat_extra_legroom_fee"]),
        exit_row_available=int(row["seat_exit_row_available"]),
        exit_row_fee=float(row["seat_exit_row_fee"]),
    )


def _load_extended_csv() -> list[FlightInventoryItem]:
    csv_path = Path(__file__).parent / "seed_data_extended.csv"
    with csv_path.open(encoding="utf-8", newline="") as f:
        return [
            FlightInventoryItem(
                flight_id=row["flight_id"],
                carrier=row["carrier"],
                flight_no=row["flight_no"],
                origin_airport=row["origin_airport"],
                dest_airport=row["dest_airport"],
                dep_ts=row["dep_ts"],
                arr_ts=row["arr_ts"],
                duration_min=int(row["duration_min"]),
                price=float(row["price"]),
                cabin_class=row["cabin_class"],
                seats_available=int(row["seats_available"]),
                stops=int(row["stops"]),
                wheelchair_assist_available=row["wheelchair_assist_available"].strip().lower() in _TRUE_STRINGS,
                step_free_boarding=row["step_free_boarding"].strip().lower() in _TRUE_STRINGS,
                seat_inventory=_seat_inventory_from_row(row),
            )
            for row in csv.DictReader(f)
        ]


GOLDEN_SCENARIO_FLIGHTS: list[FlightInventoryItem] = [
    # Outbound SIN -> NRT, 2026-09-01
    FlightInventoryItem(
        flight_id="SQ636-20260901",
        carrier="SQ",
        flight_no="SQ636",
        origin_airport="SIN",
        dest_airport="NRT",
        dep_ts="2026-09-01T16:00+08:00",
        arr_ts="2026-09-01T23:40+09:00",
        duration_min=400,
        price=380,
        cabin_class="ECONOMY",
        seats_available=12,
        stops=0,
        wheelchair_assist_available=True,
        step_free_boarding=True,
    ),
    FlightInventoryItem(
        flight_id="SQ632-20260901",
        carrier="SQ",
        flight_no="SQ632",
        origin_airport="SIN",
        dest_airport="NRT",
        dep_ts="2026-09-01T08:00+08:00",
        arr_ts="2026-09-01T15:10+09:00",
        duration_min=370,
        price=520,
        cabin_class="ECONOMY",
        seats_available=9,
        stops=0,
        wheelchair_assist_available=True,
        step_free_boarding=True,
    ),
    # Return NRT -> SIN, 2026-09-05
    FlightInventoryItem(
        flight_id="SQ637-20260905",
        carrier="SQ",
        flight_no="SQ637",
        origin_airport="NRT",
        dest_airport="SIN",
        dep_ts="2026-09-05T23:00+09:00",
        arr_ts="2026-09-06T04:40+08:00",
        duration_min=400,
        price=390,
        cabin_class="ECONOMY",
        seats_available=8,
        stops=0,
        wheelchair_assist_available=True,
        step_free_boarding=True,
    ),
    FlightInventoryItem(
        flight_id="SQ633-20260905",
        carrier="SQ",
        flight_no="SQ633",
        origin_airport="NRT",
        dest_airport="SIN",
        dep_ts="2026-09-05T11:00+09:00",
        arr_ts="2026-09-05T17:00+08:00",
        duration_min=420,
        price=520,
        cabin_class="ECONOMY",
        seats_available=10,
        stops=0,
        wheelchair_assist_available=True,
        step_free_boarding=True,
    ),
]

SEED_FLIGHT_INVENTORY: list[FlightInventoryItem] = GOLDEN_SCENARIO_FLIGHTS + _load_extended_csv()

# What this dataset can actually answer, derived from the rows themselves.
#
# Coverage used to be a hand-maintained country list (`SEED_BACKED_COUNTRIES`),
# which had to be edited in lockstep with the CSV and silently went stale when
# it wasn't. Deriving it means regenerating the CSV updates coverage for free,
# and it answers at the granularity route matching actually uses — an airport
# pair, not a country.
SEED_AIRPORTS: frozenset[str] = frozenset(
    code
    for item in SEED_FLIGHT_INVENTORY
    for code in (item.origin_airport, item.dest_airport)
)

SEED_ROUTES: frozenset[tuple[str, str]] = frozenset(
    (item.origin_airport, item.dest_airport) for item in SEED_FLIGHT_INVENTORY
)


def covers_route(origins: list[str] | tuple[str, ...], dests: list[str] | tuple[str, ...]) -> bool:
    """Whether any origin/destination airport pair has rows in this dataset.

    Any pair, not every pair: a traveller flying London -> Tokyo picks a city
    served by four airports, and the trip is answerable if even one of the
    resulting pairs is stocked.
    """
    return any((origin, dest) in SEED_ROUTES for origin in origins for dest in dests)
