"""Layered guardrails.

    L0  pydantic schemas          `schemas.py`               structural
    L1  regex / keyword detectors `agents/*/guardrails.py`   syntactic
    L2  LLM classifier            this package               semantic

Each layer can block on its own and L2 runs last, so a request only reaches the
classifier once the cheap deterministic checks have already cleared it. That
ordering is the point: it keeps L0/L1's guarantees intact and independently
arguable, bounds L2's false-negative rate from below, and means obviously-bad
input is rejected without an API call.

`docs/security/guardrail-eval-report.md` reports what each layer contributes,
generated by `scripts/guardrail_eval.py` from the corpus in `tests/adversarial/`.
"""

from flaskapp.travel_ai.guardrails.classifier import (
    LlmGuardrail, build_guardrail, guardrail_settings,
)
from flaskapp.travel_ai.guardrails.fields import collect_free_text
from flaskapp.travel_ai.guardrails.schema import GUARDRAIL_PROMPT_VERSION, GuardrailVerdict
from flaskapp.travel_ai.guardrails.types import Category, Decision, Verdict

__all__ = [
    "GUARDRAIL_PROMPT_VERSION",
    "Category",
    "Decision",
    "GuardrailVerdict",
    "LlmGuardrail",
    "Verdict",
    "build_guardrail",
    "collect_free_text",
    "guardrail_settings",
]
